### ISSUE TITLE
problem about  ESCCD_strem  datasets

### ISSUE THREAD

**Issue by tian961214** [nijkah/MaskTrack_Box#2]
Hello, I am very interested in your work. I saw that the ESCCD_strem data set is called in the ESCCD function in the dataset_pair.py function in your training data set. How did you get this data set?

**Comment by nijkah** [comment]
Thank you for your interests!

Do you mean **Extended Complex Scene Saliency Dataset (ECSSD)**?
You can find it from the [official page](http://www.cs.cuhk.edu.hk/~leojia/projects/hsaliency/dataset.html) or [my code](https://github.com/nijkah/MaskTrack_Box/blob/master/data/download_datasets.sh).

And **Dreaming** indicates that I augmented the original dataset by [Lucid Data Dreaming](https://github.com/yelantf/pyLucid).
